module.exports = {
  name: 'yuhelp',
  aliases: ['yh', 'yuguide', 'yuhow'],
  exp: 0,
  cool: 5,
  react: '📖',
  category: 'yu-gi-oh-cards',
  usage: 'Use {prefix}yuhelp',
  description: 'Complete guide on how to play Yu-Gi-Oh in this bot',
  async execute(client, arg, M) {
    const p = client.prefix

    const guide = [
      `🃏 *YU-GI-OH GUIDE* 🃏`,
      ``,
      `━━━━━━━━━━━━━━━━━━━━`,
      `📦 *GETTING CARDS*`,
      `━━━━━━━━━━━━━━━━━━━━`,
      `• *${p}yuget* — Claim a free random card (cooldown applies)`,
      `• *${p}yuclaim* — Claim daily free cards`,
      `• *${p}yugioh <name|id>* — Look up any Yu-Gi-Oh card`,
      `• *${p}yusummon [index]* — Battle a wild spawned card. Win = capture it!`,
      ``,
      `━━━━━━━━━━━━━━━━━━━━`,
      `🗂 *MANAGING YOUR CARDS*`,
      `━━━━━━━━━━━━━━━━━━━━`,
      `• *${p}yucollection* — View your full card collection`,
      `• *${p}yudeck* — View your battle deck`,
      `• *${p}t2yudeck <index>* — Move a card from collection → deck`,
      `• *${p}t2yucollec <index>* — Move a card from deck → collection`,
      `• *${p}swapyu <deck#> <coll#>* — Swap a deck card with a collection card`,
      `• *${p}discard <index>* — Discard a card from collection for gems`,
      ``,
      `━━━━━━━━━━━━━━━━━━━━`,
      `⚔️ *BATTLING*`,
      `━━━━━━━━━━━━━━━━━━━━`,
      `*Challenge Flow:*`,
      `1️⃣ *${p}yubattle @user [deckIndex]* — Challenge someone to a duel`,
      `   OR use *${p}ych @user* — Quick challenge (auto-picks your best card)`,
      `2️⃣ *${p}yuaccept [deckIndex]* — Accept the challenge with your card`,
      `   OR use *${p}ych --accept* — Auto-picks your best card`,
      `3️⃣ Result is shown instantly with a *battlefield image*`,
      ``,
      `*Battle Rules:*`,
      `• Challenger ATK vs Acceptor DEF → If ATK > DEF, challenger wins`,
      `• Otherwise Acceptor ATK vs Challenger DEF → If ATK > DEF, acceptor wins`,
      `• If neither, it's a *DRAW*`,
      `• Winner earns *20% of loser's card price* in gems (min 500💎)`,
      `• 👑 Gold members earn *1.5×* the gem reward`,
      ``,
      `*Wild Card Summon:*`,
      `• *${p}yusummon [deckIndex]* — Battle a random wild card`,
      `• Win = wild card captured into your collection + gems`,
      `• Lose = the card escapes`,
      ``,
      `*Other Battle Commands:*`,
      `• *${p}ych --decline* — Decline a challenge`,
      `• *${p}ych --cancel* — Cancel your own pending challenge`,
      `• *${p}yudecline* — Decline a duel challenge`,
      `• *${p}yubattlestatus* — Check if there's a pending duel in the group`,
      ``,
      `━━━━━━━━━━━━━━━━━━━━`,
      `💰 *TRADING & ECONOMY*`,
      `━━━━━━━━━━━━━━━━━━━━`,
      `• *${p}sale <index> <price>* — List a collection card for sale`,
      `• *${p}purchase <id>* — Buy a card listed for sale`,
      `• *${p}yutrade @user <yourUID> <theirUID>* — Propose a card trade`,
      `• *${p}yutrade-confirm* — Confirm a pending trade`,
      `• *${p}yutrade-delete* — Cancel a pending trade`,
      `• *${p}giveyucard @user <uid>* — Gift a card to someone`,
      ``,
      `━━━━━━━━━━━━━━━━━━━━`,
      `👑 *PREMIUM FEATURES*`,
      `━━━━━━━━━━━━━━━━━━━━`,
      `*Gold Membership 🥇*`,
      `• 60-card deck limit (vs 40 for free)`,
      `• 12-slot Pokémon party (vs 6 for free)`,
      `• 1.5× gem reward in duels`,
      `• Gold badge 👑`,
      ``,
      `*Max Party 🎯*`,
      `• 12-slot Pokémon party`,
      ``,
      `Contact the owner to purchase premium!`,
      `Use *${p}premium* to check your status.`,
      ``,
      `━━━━━━━━━━━━━━━━━━━━`,
      `💡 *TIPS*`,
      `━━━━━━━━━━━━━━━━━━━━`,
      `• High ATK cards = great for attacking`,
      `• High DEF cards = great for defending against challenges`,
      `• Use *${p}ych* for quick battles — it picks your strongest card automatically`,
      `• Summon wild cards daily to grow your collection for free`
    ].join('\n')

    return client.sendMessage(
      M.from,
      { text: guide },
      { quoted: M }
    )
  }
}
